export const ORE_GLYPHS: Record<string, string[]> = {
  emberite: [
    "..oooo..",
    ".oBBBbo.",
    "oBccBBbo",
    "oBcBBBbo",
    "obBBBBbo",
    ".obbBbo.",
    "..oooo..",
    "........",
  ],
  coldiron: [
    "...o....",
    "..oBBo..",
    ".oBcBBo.",
    "oBBcBBbo",
    "obBBBBbo",
    ".obbBbo.",
    "..oooo..",
    "........",
  ],
  stormore: [
    "....o...",
    "..oBBo..",
    ".oBcBBo.",
    "oBBBBBbo",
    "oBbBBbbo",
    ".oBBboo.",
    "..oooo..",
    "........",
  ],
  voidslag: [
    "..oooo..",
    ".obbbbo.",
    "ob....bo",
    "ob.cc.bo",
    "ob....bo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  thornite: [
    "...o.o..",
    ".o.b.o..",
    "o.bBb.o.",
    ".obBBbo.",
    "oobBBboo",
    ".obbbbo.",
    "..o.o...",
    "........",
  ],
  blastore: [
    ".oooooo.",
    "obBccBbo",
    "oBBbbBBo",
    "obb..bbo",
    "oBB..BBo",
    "obBBBBbo",
    ".oooooo.",
    "........",
  ],
  goldvein: [
    "..oooo..",
    ".obcBbo.",
    "obBcBBbo",
    "oBBBcBbo",
    "obBBcBbo",
    ".obbBbo.",
    "..oooo..",
    "........",
  ],
  nightiron: [
    ".oooooo.",
    "obbbbbbo",
    "obBccBbo",
    "obBBBbbo",
    "obbbbbbo",
    "obbbbbbo",
    ".oooooo.",
    "........",
  ],
  mossore: [
    "..o..o..",
    ".obooBo.",
    "obBBbBbo",
    "oBbccbBo",
    "obBBBBbo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  bloodstone: [
    "..oooo..",
    ".oBBBBo.",
    "oBccBBbo",
    "oBBBBBbo",
    ".obbBbo.",
    "..obbo..",
    "...oo...",
    "....o...",
  ],
  moonslag: [
    "...ooo..",
    "..oBBBo.",
    ".oBc..bo",
    "oBB...bo",
    "oBB..bbo",
    ".oBBBBo.",
    "..oooo..",
    "........",
  ],
  ashvein: [
    "..o.oo..",
    ".obBbBo.",
    "oBb.cBbo",
    "obBBBBbo",
    "oBbBbBbo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  rimeore: [
    "...c....",
    "..oBBo..",
    ".oBcBBo.",
    "oBBBBBbo",
    "obBcBBbo",
    ".oBBBBo.",
    "..oooo..",
    "........",
  ],
  brambleiron: [
    ".o..o.o.",
    "o.obBo.o",
    ".obBBbo.",
    "oobccboo",
    ".obBBbo.",
    "o.obbo.o",
    ".o..o.o.",
    "........",
  ],
  starslag: [
    "...c....",
    "..oBo...",
    ".oBBBo..",
    "cBBBBBBc",
    ".oBBBo..",
    "..oBo...",
    "...c....",
    "........",
  ],
};

export const CRYSTAL_GLYPHS: Record<string, string[]> = {
  "cinder-crystal": [
    "...oo...",
    "..oCCo..",
    ".oCcCCo.",
    "oCcccCCo",
    "oCcccCCo",
    ".oCCCCo.",
    "..oooo..",
    "........",
  ],
  "frost-crystal": [
    "...c....",
    "..oCo...",
    ".oCcCo..",
    "oCcccCo.",
    ".oCcCo..",
    "..oCo...",
    "...o....",
    "........",
  ],
  "bolt-crystal": [
    "....c...",
    "...oCo..",
    "..oCCCo.",
    ".oCcccC.",
    "oCCCCCo.",
    ".oooo...",
    "..o.....",
    "........",
  ],
  "void-crystal": [
    "..oooo..",
    ".oCCCCo.",
    "oC....Co",
    "oC....Co",
    "oC....Co",
    ".oCCCCo.",
    "..oooo..",
    "........",
  ],
  "vine-crystal": [
    "...o.o..",
    "..oCoCo.",
    ".oCcCCo.",
    "oCcccCCo",
    ".oCCCCo.",
    "..o.o...",
    "...o....",
    "........",
  ],
  "boom-crystal": [
    "..oooo..",
    ".oCCCCo.",
    "oCcCCcCo",
    "oCCCCCCo",
    "oCcCCcCo",
    ".oCCCCo.",
    "..oooo..",
    "........",
  ],
  "dawn-crystal": [
    "...oo...",
    "..oCCo..",
    ".oCCCCo.",
    "oCCccCCo",
    ".oCCCCo.",
    "..oooo..",
    "...oo...",
    "........",
  ],
  "dusk-crystal": [
    ".oooooo.",
    "oCCCCCCo",
    "oCCccCCo",
    "oCccccCo",
    ".oCCCCo.",
    "..oooo..",
    "...oo...",
    "........",
  ],
  "heart-crystal": [
    ".oo..oo.",
    "oCCooCCo",
    "oCCccCCo",
    ".oCccCo.",
    "..oCCo..",
    "...oo...",
    "........",
    "........",
  ],
  "grave-crystal": [
    ".oooooo.",
    "oCCCCCCo",
    "oC....Co",
    "oC.cc.Co",
    "oC....Co",
    "oCCCCCCo",
    ".oooooo.",
    "........",
  ],
  "tide-crystal": [
    "...oo...",
    ".ooCCoo.",
    "oCCccCCo",
    "oCccccCo",
    ".oCCCCo.",
    "..oCCo..",
    "...oo...",
    "........",
  ],
  "spark-crystal": [
    "c..o..c.",
    ".oCCCo..",
    "oCcccCo.",
    "oCcccCo.",
    ".oCCCo..",
    "..o.o...",
    ".c...c..",
    "........",
  ],
  "bloom-crystal": [
    "..o.c.o.",
    ".oCoCoCo",
    "oCCccCCo",
    ".oCCCCo.",
    "..oCCo..",
    "...oo...",
    "........",
    "........",
  ],
  "shade-crystal": [
    "..oooo..",
    ".obbbbo.",
    "obCccCbo",
    "oCccccCo",
    "obCCCCbo",
    ".obbbbo.",
    "..oooo..",
    "........",
  ],
  "lantern-crystal": [
    "...oo...",
    "..oCCo..",
    ".oCccCo.",
    "oCCccCCo",
    ".oooooo.",
    "...hh...",
    "...hh...",
    "........",
  ],
};

export const WEAPON_GLYPHS: Record<string, string[]> = {
  "ember-mallet": [
    "......................",
    "..............oooo....",
    ".............oBBBBo...",
    "............oBcCCBBo..",
    ".ohHHHHHho..oBBBBBBo..",
    ".ohhhhhhho...oBBBBo...",
    "..oooooo......oooo....",
    "......................",
  ],
  "ice-peen": [
    "......................",
    ".................oC...",
    "...............ooCCo..",
    ".ohHHHHHHHHoooBBBCCo..",
    ".ohhhhhhhhhoooBBBBo...",
    "..oooooooo....ooo.....",
    "......................",
    "......................",
  ],
  "storm-hammer": [
    "......................",
    "............ooooooo...",
    "...........oBBCCBBo...",
    ".ohHHHHHho.oBBBBBBo...",
    ".ohhhhhhho.oBBBBBBo...",
    "..oooooo....oBBBoo....",
    "..............o.......",
    "......................",
  ],
  "void-maul": [
    "......................",
    "..........oooooooo....",
    ".........oBB....BBo...",
    ".ohHHHho.oB.oCCo.Bo...",
    ".ohhhhho.oB.oCCo.Bo...",
    "..ooooo..oBB....BBo...",
    "..........oooooooo....",
    "......................",
  ],
  "thorn-hammer": [
    "......................",
    "....o.........o..o....",
    "...o.o......ooBBo.o...",
    ".ohHHHHHHoooBBCCBo....",
    ".ohhhhhhhoooBBBBoo....",
    "...o.o......ooo.o.....",
    "....o.........o.......",
    "......................",
  ],
  "blast-sledge": [
    "......................",
    ".........oooooooooo...",
    "........oBBCcCCBBBo...",
    ".ohHHho.oBBBBBBBBBo...",
    ".ohhhho.oBBBBBBBBBo...",
    "..oooo...oBBBBBBBo....",
    "..........ooooooo.....",
    "......................",
  ],
  "gold-hammer": [
    "......................",
    "...........o.ooo.o....",
    "..........oBBCCBBo....",
    ".ohHHHHHo.oBcCCcBo....",
    ".ohhhhhho.oBBBBBBo....",
    "..oooooo...oBBBBo.....",
    "............oooo......",
    "......................",
  ],
  "night-maul": [
    "......................",
    ".........oo....oo.....",
    "........oBBBooBBBo....",
    ".ohHHHhooBBCCBBBBo....",
    ".ohhhhhooBBBBBBBBo....",
    "..ooooo..oBBBBBBo.....",
    "..........oooooo......",
    "......................",
  ],
  "root-mallet": [
    "......................",
    ".............o.oo.....",
    "............oBbBBo....",
    ".oHhHhHho..oBccBBo....",
    ".ohhHhHho..oBBBBoo....",
    "..oooooo....oBBo......",
    ".............oo.......",
    "......................",
  ],
  "bone-hammer": [
    "......................",
    ".................oC...",
    "................oBBo..",
    ".oHhHhHhHhHooooBBBo...",
    ".ohhHhHhHhHooooBBBo...",
    "................oBBo..",
    ".................oC...",
    "......................",
  ],
  "moon-peen": [
    "......................",
    "...................oC.",
    ".................ooCCo",
    ".ohHHHHHHHHHHHo.oBBCo.",
    ".ohhhhhhhhhhhho.oBBo..",
    "..oooooooooooo...oo...",
    "......................",
    "......................",
  ],
  "ash-sledge": [
    "......................",
    "........ooooooooooo...",
    ".......oBBo.c.oBBBo...",
    ".ohHHHo.oBBBBBBBBBo...",
    ".ohhhho.oBBBBBBBBBo...",
    "..oooo...oBBBBBBBo....",
    "..........ooooooo.....",
    "......................",
  ],
  "rime-hammer": [
    "......................",
    "............oCcCo.....",
    "...........oBCCBBo....",
    ".ohHHHHHo..oBBBBBo....",
    ".ohhhhhho..oBBBBBo....",
    "..oooooo....oCcCo.....",
    "......................",
    "......................",
  ],
  "bramble-maul": [
    "......................",
    "....o...oooo...o......",
    "...o.o.oBCCBo.o.o.....",
    ".ohHHHooBBBBBoo.......",
    ".ohhhhooBBBBBoo.......",
    "...o.o..oooo.o.o......",
    "....o.........o.......",
    "......................",
  ],
  "star-hammer": [
    "......................",
    ".................c.oC.",
    "..............o.oBBCo.",
    ".ohHHHHHHHHHHo.oBBBBo.",
    ".ohhhhhhhhhhho.oBBBo..",
    "..............o.oBo...",
    ".................c....",
    "......................",
  ],
};

function shade(hex: string, amt: number) {
  const n = parseInt(hex.replace("#", ""), 16);
  const r = Math.max(0, Math.min(255, ((n >> 16) & 255) + amt));
  const g = Math.max(0, Math.min(255, ((n >> 8) & 255) + amt));
  const b = Math.max(0, Math.min(255, (n & 255) + amt));
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`;
}

export function weaponGlyph(hammerId: string): string[] {
  return WEAPON_GLYPHS[hammerId] ?? WEAPON_GLYPHS["ember-mallet"]!;
}

export function pieceGlyph(id: string): string[] {
  return ORE_GLYPHS[id] ?? CRYSTAL_GLYPHS[id] ?? weaponGlyph(id);
}

export function piecePalette(id: string, color: string, crystal = "#fff4c8"): Record<string, string> {
  return {
    o: "#1a1210",
    h: "#2a1c14",
    H: "#7a5230",
    b: shade(color, -24),
    B: color,
    c: shade(crystal, -10),
    C: crystal,
  };
}

export function drawWeaponGlyph(
  ctx: CanvasRenderingContext2D,
  hammerId: string,
  x: number,
  y: number,
  ang: number,
  px: number,
  ore: string,
  crystal: string,
  flash = false,
) {
  const rows = weaponGlyph(hammerId);
  const h = rows.length;
  const w = rows[0]?.length ?? 1;
  const pal = piecePalette(hammerId, flash ? "#fff4c8" : ore, flash ? "#ffffff" : crystal);
  ctx.save();
  ctx.imageSmoothingEnabled = false;
  ctx.translate(x, y);
  ctx.rotate(ang);
  const ox = 1;
  const oy = -Math.floor(h / 2);
  for (let j = 0; j < h; j++) {
    const row = rows[j]!;
    for (let i = 0; i < w; i++) {
      const ch = row[i]!;
      if (ch === ".") continue;
      ctx.fillStyle = pal[ch] ?? ore;
      ctx.fillRect((ox + i) * px, (oy + j) * px, px, px);
    }
  }
  ctx.restore();
}
